services:
  frontend:
    build: ./frontend/esiedt-app
    container_name: esiedt_frontend
    restart: unless-stopped
    # Plus besoin d'exposer les ports à la machine hôte
    depends_on:
      - backend
    networks:
      - caddy_net # À remplacer par le nom exact de votre réseau Caddy

  backend:
    build: ./backend
    container_name: esiedt_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
    name: caddy_net