services:
  frontend:
    build: ./frontend/esiedt-app
    container_name: esiedt_frontend
    restart: unless-stopped
    # Plus besoin d'exposer les ports à la machine hôte
    depends_on:
      - backend
    networks:
      - caddy_net # À remplacer par le nom exact de votre réseau Caddy

  backend:
    build: ./backend
    container_name: esiedt_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - caddy_net

  umami-db:
    image: postgres:15-alpine
    container_name: esiedt_umami_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: xuwVBjv4hPJlONDGlcCgYFgHU37Pep-ur0HTAvbQwUVdriUDDxhbcZsuRdbM
    volumes:
      - umami_db_data:/var/lib/postgresql/data
    networks:
      - caddy_net

  umami:
    image: docker.umami.is/umami-software/umami:postgresql-latest
    container_name: esiedt_umami
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://umami:xuwVBjv4hPJlONDGlcCgYFgHU37Pep-ur0HTAvbQwUVdriUDDxhbcZsuRdbM@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: auV1MUfW2ztWW9XmJe9ucZ1DLjX42dSfbrHCa20mK33-GO8FvTTzM83uFGli
      BASE_PATH: /stats
    depends_on:
      - umami-db
    networks:
      - caddy_net


networks:
  caddy_net:
    external: true
    name: caddy_net

volumes:
  umami_db_data:
